-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\simulink_implementation\HDL_DUT_tc.vhd
-- Created: 2019-12-29 14:04:17
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_DUT_tc
-- Source Path: HDL_DUT_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_2600_0: 2600x slower than clk with last phase
-- enb_1_2600_1: 2600x slower than clk with phase 1
-- enb_1_2600_4: 2600x slower than clk with phase 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_DUT_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_2600_0                      :   OUT   std_logic;
        enb_1_2600_1                      :   OUT   std_logic;
        enb_1_2600_4                      :   OUT   std_logic
        );
END HDL_DUT_tc;


ARCHITECTURE rtl OF HDL_DUT_tc IS

  -- Signals
  SIGNAL count2600                        : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_4                          : std_logic;
  SIGNAL phase_4_tmp                      : std_logic;

BEGIN
  Counter2600 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        count2600 <= to_unsigned(1, 12);
      ELSIF clk_enable = '1' THEN
        IF count2600 >= to_unsigned(2599, 12) THEN
          count2600 <= to_unsigned(0, 12);
        ELSE
          count2600 <= count2600 + to_unsigned(1, 12);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter2600;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        phase_0 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count2600 = to_unsigned(2599, 12) AND clk_enable = '1' ELSE '0';

  temp_process2 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        phase_1 <= '1';
      ELSIF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  phase_1_tmp <= '1' WHEN count2600 = to_unsigned(0, 12) AND clk_enable = '1' ELSE '0';

  temp_process3 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        phase_4 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_4 <= phase_4_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process3;

  phase_4_tmp <= '1' WHEN count2600 = to_unsigned(3, 12) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_2600_0 <=  phase_0 AND clk_enable;

  enb_1_2600_1 <=  phase_1 AND clk_enable;

  enb_1_2600_4 <=  phase_4 AND clk_enable;


END rtl;

